site_name: ServiLive Docs
site_url: https://docs.servilive.cl
theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow

nav:
  - Home: index.md
  - Reglas:
    - Generales: reglas/generales.md
    - Servidor de Discord: reglas/discord.md
    - Servidores de juego: reglas/juegos.md
    - Versus Saxton Hale: reglas/vsh.md
    - Jailbreak: reglas/jb.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
