site_name: Servilive 
site_url: https://docs.servilive.cl
theme:
  logo: assets/ss.svg
  favicon: assets/servilive-64.png
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.indexes
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/brightness-auto
        name: Cambiar a modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a las preferencias del sistema

nav:
  - Inicio: index.md
  - Reglas:
    - Introducción: reglas/intro.md
    - Reglas de conducta: reglas/conducta.md
    - Reglas de juego: reglas/juegos.md
    - Reglas de modos de juego: reglas/gamemodes.md
  - Comandos:
    - Usuarios: others/usuarios.md
    - VIPs: others/vips.md
    - Staff: others/staff.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cfYHjJ7RSZ
    - icon: fontawesome/brands/github
      link: https://github.com/servilive/docs
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/groups/Servilive

copyright: Copyright &copy; 2023 - 2023 ServiLive